# Generated by Django 4.2.26 on 2025-11-12 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kicker', models.CharField(default='Our mission', max_length=120)),
                ('headline', models.CharField(max_length=255)),
                ('intro', models.TextField()),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='AudienceSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(default='👤', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kicker', models.CharField(default='We are here to help', max_length=120)),
                ('headline', models.CharField(max_length=255)),
                ('intro', models.TextField()),
                ('support_email', models.EmailField(default='support@insurancebuddy.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_kicker', models.CharField(default='For international students in the U.S.', max_length=120)),
                ('hero_headline', models.CharField(max_length=255)),
                ('hero_subheadline', models.TextField()),
                ('primary_cta_label', models.CharField(default='Compare Plans', max_length=80)),
                ('primary_cta_url', models.CharField(default='/product/', max_length=255)),
                ('secondary_cta_label', models.CharField(default='Learn more', max_length=80)),
                ('secondary_cta_url', models.CharField(default='/about/', max_length=255)),
                ('trust_heading', models.CharField(default='Trusted by students', max_length=255)),
                ('trust_body', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='PartnerOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('campus', models.CharField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(verbose_name='Logo URL')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'University partner',
                'verbose_name_plural': 'University partners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kicker', models.CharField(default='Plan builder', max_length=120)),
                ('headline', models.CharField(max_length=255)),
                ('subheadline', models.TextField()),
                ('summary_line', models.CharField(blank=True, max_length=255)),
                ('summary_secondary', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Product Page Content',
                'verbose_name_plural': 'Product Page Content',
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='insurance_aggregator.homepagecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='✨', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='insurance_aggregator.homepagecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='💡', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='insurance_aggregator.aboutpagecontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
